### ISSUE TITLE
Strart service without login user.

### ISSUE THREAD

**Issue by khseal** [spmp/promiscuous-bluetooth-audio-sinc#3]
The service does not work if the user is not logged in or logged out.
I added autologin on the server only then it worked.

**Comment by spmp** [comment]
Can you outline the steps you have taken please.
The `systemd` service running would run as root as is. I have slight changes on my end which runs the process as `pipewire` user. I will update the documentation soon to include checks on this.

**Comment by khseal** [comment]
This instruction helped me. Although it is possible to have another method.
![image](https://github.com/spmp/promiscuous-bluetooth-audio-sinc/assets/11374629/5c35fd29-c738-40ea-8fd6-bb65e389c8b3)

**Comment by spmp** [comment]
I am glad the instructions helped, is this resolved for you?
