### ISSUE TITLE
Auto-connect after server restart no work.

### ISSUE THREAD

**Issue by khseal** [spmp/promiscuous-bluetooth-audio-sinc#4]
Autoconnect does not work if you restart the server. 
Can this problem be fixed?

**Comment by spmp** [comment]
Can you outline the steps taken please?
This is not bulletproof for me either and sometimes both the agent and PipewirePulse need restarting.
There is sometimes contention when a PipeWire _pro_ device with both Pulse Tunnel streams and Bluetooth.

**Comment by khseal** [comment]
I used this script. https://github.com/jrouleau/bluetooth-autoconnect
But he does not solve the problem. My phone if it has lost the connection after some time stops trying to automatically connect and does not connect with this script. I need to check on other phones.

**Comment by spmp** [comment]
Oh dear, yes that does sound like it may be a phone issue.
Please let me know what you discover and close this issue as you see appropriate.
Good luck!
